"""
ReportAgent — generates a final structured Markdown research report.
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from state import ResearchState


REPORT_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a professional research report writer. Generate a comprehensive, 
well-structured Markdown research report based on the provided research data.

The report MUST follow this structure:

# [Generate a descriptive title]

## Executive Summary
[2-3 paragraph overview]

## Key Findings
[Bullet points of main findings]

## Detailed Analysis
[In-depth analysis organised by themes/subtopics]

## Fact-Check Results
[Summary of verified claims with status indicators]
- ✅ Confirmed claims
- ⚠️ Conflicting claims  
- ❓ Unverified claims

## Sources
[Numbered list of all sources with URLs]

---
*Generated by Multi-Agent Research Assistant*

Make the report detailed, professional, and well-formatted in Markdown.
Also generate a concise report title (without the # prefix)."""),
    ("human", """Research Query: {query}

Summary:
{summary}

Fact-Check Results:
{fact_check_data}

Sources:
{sources_data}

Generate the complete Markdown research report."""),
])


def report_agent(state: ResearchState) -> dict:
    """
    Generate a final structured Markdown report from all research data.

    Combines the summary, fact-check results, and source citations
    into a professional research document with one-click export.
    """
    errors = list(state.get("errors", []))

    # Format fact-check data
    fact_check_data = f"Overall: {state.get('fact_check_summary', 'N/A')}\n\n"
    for claim in state.get("verified_claims", []):
        status_icon = {
            "confirmed": "✅",
            "conflicting": "⚠️",
            "unverified": "❓",
        }.get(claim.get("status", ""), "❓")
        fact_check_data += (
            f"{status_icon} [{claim.get('status', 'unknown').upper()}] "
            f"{claim.get('statement', '')}\n"
            f"   Evidence: {claim.get('evidence', 'N/A')}\n\n"
        )

    # Format sources
    sources_data = ""
    for i, src in enumerate(state.get("sources", []), 1):
        sources_data += f"{i}. [{src['title']}]({src['url']})\n"
        sources_data += f"   {src['snippet'][:150]}...\n\n"

    try:
        llm = ChatGroq(
            model="llama-3.1-8b-instant",
            temperature=0.3,
            max_tokens=4096,
        )

        chain = REPORT_PROMPT | llm
        response = chain.invoke({
            "query": state["query"],
            "summary": state.get("summary", "No summary available."),
            "fact_check_data": fact_check_data,
            "sources_data": sources_data,
        })

        report = response.content.strip()

        # Extract title from the first heading
        report_title = state["query"]
        for line in report.split("\n"):
            if line.startswith("# "):
                report_title = line.lstrip("# ").strip()
                break

        print(f"[ReportAgent] Generated report: '{report_title}' "
              f"({len(report)} chars)")

    except Exception as e:
        report = f"# Research Report: {state['query']}\n\nError generating report: {str(e)}"
        report_title = f"Research: {state['query']}"
        errors.append(f"ReportAgent error: {str(e)}")
        print(f"[ReportAgent] Error: {e}")

    return {
        "report": report,
        "report_title": report_title,
        "errors": errors,
    }
